# Generated by Django 4.0.10 on 2025-02-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_generado', models.CharField(max_length=4)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ingresado', models.CharField(max_length=4)),
                ('puntos', models.IntegerField()),
                ('famas', models.IntegerField()),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.partida')),
            ],
        ),
    ]
